import type { GetServerSidePropsContext, Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Layout from "@/components/Layout";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { StoreProvider } from "@/store/index";
import { IRootStore } from "@/store/rootStore";
import { cookies } from "next/headers";
// import ErrorBoundary from "@/components/ErrorBoundary";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cokiesObj = cookies();
  // console.log("cookiesObj=", cokiesObj);
  // console.log(
  //   "userId=",
  //   cokiesObj.get("userId"),
  //   cokiesObj.get("userId")?.value
  // );
  console.log(
    "main-RootLayout-cokiesObj.get-userId=",
    cokiesObj.get("userId"),
    cokiesObj.get("nickname")
  );
  const initialValues: IRootStore = {
    user: {
      userInfo: {
        userId: Number(cokiesObj.get("userId")?.value),
        nickname: cokiesObj.get("nickname")?.value,
        avatar: cokiesObj.get("avatar")?.value,
      },
    },
  };
  // console.log("RootLayout-initialValues=", initialValues);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          {/* <ErrorBoundary></ErrorBoundary> */}
          <StoreProvider initialValues={initialValues}>
            <Layout>{children}</Layout>
          </StoreProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}

// RootLayout.getInitialProps = async ({ctx}:{ctx:any}) => {
//   console.log("ctx.req.cookies=", ctx.req.cookies);
//   const { userId, nicjkname, avatar } = ctx.req.cookies || {};
//   return {
//     initialValues: {
//       user: {
//         userInfo: {
//           userId,
//           nicjkname,
//           avatar,
//         },
//       },
//     },
//   };
// };

// export async function getServerSideProps(ctx: GetServerSidePropsContext) {
//   console.log("ctx.req.cookies=", ctx.req.cookies);
//   const { userId, nicjkname, avatar } = ctx.req.cookies || {};
//   return {
//     props: {
//       initialValues: {
//         user: {
//           userInfo: {
//             userId,
//             nicjkname,
//             avatar,
//           },
//         },
//       },
//     },
//   };
// }

